{% set name = "yaqd-newport" %}
{% set version = "2020.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1db884806f25420fbe712b6d5ba80c29746fe218828d4da208bc7796e752baa6

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-newport-conex-agp = yaqd_newport._newport_conex_agp:NewportConexAGP.main
    - yaqd-newport-smc100 = yaqd_newport._newport_smc100:NewportSMC100.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - pyserial
    - yaqd-core >=2020.10.1
  run:
    - python >=3.7
    - pyserial 
    - yaqd-core >=2020.10.1

test:
  imports:
    - yaqd_newport
  commands:
    - pip check
    - yaqd-newport-conex-agp --help
    - yaqd-newport-smc100 --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Newport hardware
  dev_url: https://gitlab.com/yaq/yaqd-newport
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
